In [2]:
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()

In [3]:
a = tf.constant([9,8,7],name="a")
b = tf.constant([1,2,3],name="b")

In [4]:
soma = a + b

In [5]:
with tf.Session() as sess:
    print(sess.run(soma))

[10 10 10]


2025-01-28 23:25:38.146654: E external/local_xla/xla/stream_executor/cuda/cuda_driver.cc:152] failed call to cuInit: INTERNAL: CUDA error: Failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected
I0000 00:00:1738117538.148321    5484 mlir_graph_optimization_pass.cc:401] MLIR V1 optimization pass is not enabled


In [6]:
a1 = tf.constant([[1,2,3],[4,5,6]],name="a1")

In [7]:
b1 = tf.constant([[1,2,3],[4,5,6]],name="b1")

In [11]:
soma_ma = tf.add(a1,b1)

In [12]:
with tf.Session() as sess:
    print(sess.run(soma_ma))

[[ 2  4  6]
 [ 8 10 12]]
