In [18]:
import tensorflow as tf
import numpy as np
from tensorflow.keras import layers,models


x =np.array([[0,0],[0,1],[1,0],[1,1]],dtype=np.float32)

y = np.array([[1],[0],[0],[1]],dtype=np.float32)

In [19]:
x,y

(array([[0., 0.],
        [0., 1.],
        [1., 0.],
        [1., 1.]], dtype=float32),
 array([[1.],
        [0.],
        [0.],
        [1.]], dtype=float32))

In [20]:
model = models.Sequential()

model.add(layers.Dense(2,input_dim=2,activation="relu"))
model.add(layers.Dense(3,activation="relu"))
model.add(layers.Dense(3,activation="relu"))
model.add(layers.Dense(1,activation="sigmoid"))

model.compile(optimizer="adam",loss="binary_crossentropy",metrics=["accuracy"])

model.fit(x,y,epochs=1000)


Epoch 1/1000


/home/lucas/Área de Trabalho/curso_tensorflow/venv/lib/python3.10/site-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 533ms/step - accuracy: 0.5000 - loss: 0.6979
Epoch 2/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - accuracy: 0.7500 - loss: 0.6970
Epoch 3/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 0.7500 - loss: 0.6959
Epoch 4/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - accuracy: 0.7500 - loss: 0.6949
Epoch 5/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 0.7500 - loss: 0.6939
Epoch 6/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 0.7500 - loss: 0.6928
Epoch 7/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 0.7500 - loss: 0.6918
Epoch 8/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 0.7500 - loss: 0.6907
Epoch 9/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 0.7500 - loss: 0.6897
Epoch 10/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 0.7500 - loss: 0.6886
Epoch 11/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 0.5000 - loss: 0.6876
Epoch 12/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 0.5000 - lo

In [22]:
model.predict(x)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step


array([[0.9458582 ],
       [0.01234466],
       [0.27461705],
       [0.99318856]], dtype=float32)