In [6]:
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()

In [7]:
p = tf.placeholder("float",None)

In [8]:
operacao = p+2

In [9]:
with tf.Session() as sess:
    resultado = sess.run(operacao,feed_dict={p:[1,2,3]})
    print(resultado)

[3. 4. 5.]


In [10]:
p2 = tf.placeholder("float",[None,5])
operacao2 = p2*5

In [11]:
with tf.Session() as sess:
    dados = [[1,2,3,4,5],[6,7,8,9,10]]
    resultado = sess.run(operacao2,feed_dict={p2:dados})
    print(resultado)

[[ 5. 10. 15. 20. 25.]
 [30. 35. 40. 45. 50.]]
